import { EntitySchema } from 'typeorm';
export const entities = [
  new EntitySchema({
    name: 'users',
    tableName: 'users',
    columns: {
      id: { type: 'uuid', primary: true },
      name: { type: 'text' },
      first_name: { type: 'text' },
      last_name: { type: 'text' },
      cedula: { type: 'text', nullable: true },
      phone: { type: 'text', nullable: true },
      email: { type: 'text' },
      password_hash: { type: 'text' },
      role: { type: 'text' },
      active: { type: 'boolean' },
      status: { type: 'text' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'brands',
    tableName: 'brands',
    columns: {
      id: { type: 'uuid', primary: true },
      name: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'vehicle_models',
    tableName: 'vehicle_models',
    columns: {
      id: { type: 'uuid', primary: true },
      brand_id: { type: 'uuid' },
      name: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'categories',
    tableName: 'categories',
    columns: {
      id: { type: 'uuid', primary: true },
      name: { type: 'text' },
      description: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'locations',
    tableName: 'locations',
    columns: {
      id: { type: 'uuid', primary: true },
      name: { type: 'text' },
      city: { type: 'text' },
      province: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'suppliers',
    tableName: 'suppliers',
    columns: {
      id: { type: 'integer', primary: true },
      name: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'depots',
    tableName: 'depots',
    columns: {
      id: { type: 'integer', primary: true },
      supplier_id: { type: 'integer' },
      location_id: { type: 'uuid' },
      name: { type: 'text' },
      airport: { type: 'text', nullable: true },
      city_id: { type: 'integer', nullable: true },
      latitude: { type: 'numeric', nullable: true, precision: 10, scale: 7 },
      longitude: { type: 'numeric', nullable: true, precision: 10, scale: 7 },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'depot_scores',
    tableName: 'depot_scores',
    columns: {
      depot_id: { type: 'integer', primary: true },
      score: { type: 'numeric', precision: 4, scale: 2 },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'vehicles',
    tableName: 'vehicles',
    columns: {
      id: { type: 'uuid', primary: true },
      brand_id: { type: 'uuid' },
      model_id: { type: 'uuid' },
      category_id: { type: 'uuid' },
      location_id: { type: 'uuid' },
      supplier_id: { type: 'integer' },
      depot_id: { type: 'integer' },
      year: { type: 'integer' },
      color: { type: 'text' },
      license_plate: { type: 'text' },
      transmission: { type: 'text' },
      fuel_type: { type: 'text' },
      seats: { type: 'integer' },
      doors: { type: 'integer' },
      bag_capacity: { type: 'integer' },
      price_per_day: { type: 'numeric', precision: 12, scale: 2 },
      mileage: { type: 'integer' },
      description: { type: 'text' },
      status: { type: 'text' },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'search_contexts',
    tableName: 'search_contexts',
    columns: {
      id: { type: 'uuid', primary: true },
      affiliate: { type: 'numeric' },
      context: { type: 'jsonb' },
      results: { type: 'uuid', array: true },
      expires_at: { type: 'timestamptz' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'holds',
    tableName: 'holds',
    columns: {
      id: { type: 'uuid', primary: true },
      vehicle_id: { type: 'uuid' },
      owner_id: { type: 'text' },
      search_id: { type: 'uuid' },
      starts_at: { type: 'timestamptz' },
      ends_at: { type: 'timestamptz' },
      price_per_day: { type: 'numeric', precision: 12, scale: 2 },
      currency: { type: 'text' },
      expires_at: { type: 'timestamptz' },
      consumed: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'order_previews',
    tableName: 'order_previews',
    columns: {
      id: { type: 'uuid', primary: true },
      vehicle_id: { type: 'uuid' },
      owner_id: { type: 'text' },
      hold_id: { type: 'uuid', nullable: true },
      route: { type: 'jsonb' },
      price_per_day: { type: 'numeric', precision: 12, scale: 2 },
      total_amount: { type: 'numeric', precision: 12, scale: 2 },
      currency: { type: 'text' },
      extras: { type: 'jsonb' },
      expires_at: { type: 'timestamptz' },
      consumed: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'orders',
    tableName: 'orders',
    columns: {
      id: { type: 'uuid', primary: true },
      vehicle_id: { type: 'uuid' },
      owner_id: { type: 'text' },
      preview_id: { type: 'uuid' },
      locator: { type: 'text' },
      status: { type: 'text' },
      route: { type: 'jsonb' },
      starts_at: { type: 'timestamptz' },
      ends_at: { type: 'timestamptz' },
      price_per_day: { type: 'numeric', precision: 12, scale: 2 },
      total_amount: { type: 'numeric', precision: 12, scale: 2 },
      currency: { type: 'text' },
      extras: { type: 'jsonb' },
      vehicle_details: { type: 'jsonb' },
      driver_details: { type: 'jsonb' },
      payment_reference: { type: 'text' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'payments',
    tableName: 'payments',
    columns: {
      id: { type: 'uuid', primary: true },
      order_id: { type: 'uuid' },
      user_id: { type: 'uuid' },
      amount: { type: 'numeric', precision: 12, scale: 2 },
      currency: { type: 'text' },
      status: { type: 'text' },
      method: { type: 'text' },
      card_brand: { type: 'text' },
      card_last4: { type: 'text' },
      payment_reference: { type: 'text' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'idempotency_records',
    tableName: 'idempotency_records',
    columns: {
      owner_id: { type: 'text', primary: true },
      operation: { type: 'text', primary: true },
      key: { type: 'uuid', primary: true },
      request_hash: { type: 'text' },
      status_code: { type: 'integer' },
      response_body: { type: 'jsonb', nullable: true },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'favorites',
    tableName: 'favorites',
    columns: {
      id: { type: 'uuid', primary: true },
      user_id: { type: 'uuid' },
      vehicle_id: { type: 'uuid' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'webhook_subscriptions',
    tableName: 'webhook_subscriptions',
    columns: {
      id: { type: 'uuid', primary: true },
      owner_id: { type: 'text' },
      url: { type: 'text' },
      events: { type: 'jsonb' },
      encrypted_secret: { type: 'text', nullable: true },
      active: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'webhook_outbox',
    tableName: 'webhook_outbox',
    columns: {
      id: { type: 'uuid', primary: true },
      owner_id: { type: 'text', nullable: true },
      event_type: { type: 'text' },
      resource_id: { type: 'text' },
      data: { type: 'jsonb' },
      dispatched: { type: 'boolean' },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
  new EntitySchema({
    name: 'webhook_delivery_attempts',
    tableName: 'webhook_delivery_attempts',
    columns: {
      id: { type: 'uuid', primary: true },
      event_id: { type: 'uuid' },
      subscription_id: { type: 'uuid' },
      attempt_count: { type: 'integer' },
      status: { type: 'text' },
      next_attempt_at: { type: 'timestamptz' },
      last_error: { type: 'text', nullable: true },
      last_status: { type: 'integer', nullable: true },
      created_at: { type: 'timestamptz', createDate: true },
      updated_at: { type: 'timestamptz', updateDate: true },
    },
  }),
];
