import type { MigrationInterface, QueryRunner } from 'typeorm';
export class InitialSchema1790200000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE users (id uuid PRIMARY KEY, name text NOT NULL, email text NOT NULL UNIQUE, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('CUSTOMER','ADMIN')), active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE brands (id uuid PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vehicle_models (id uuid PRIMARY KEY, brand_id uuid NOT NULL REFERENCES brands(id), name text NOT NULL, active boolean NOT NULL DEFAULT true, UNIQUE(id,brand_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE categories (id uuid PRIMARY KEY, name text NOT NULL, description text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE locations (id uuid PRIMARY KEY, name text NOT NULL, city text NOT NULL, province text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE suppliers (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE depots (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id integer NOT NULL REFERENCES suppliers(id), location_id uuid NOT NULL REFERENCES locations(id), name text NOT NULL, airport text, city_id integer, latitude numeric(10,7), longitude numeric(10,7), active boolean NOT NULL DEFAULT true, UNIQUE(id,supplier_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE depot_scores (depot_id integer PRIMARY KEY REFERENCES depots(id), score numeric(4,2) NOT NULL CHECK(score BETWEEN 0 AND 10), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vehicles (id uuid PRIMARY KEY, brand_id uuid NOT NULL REFERENCES brands(id), model_id uuid NOT NULL, category_id uuid NOT NULL REFERENCES categories(id), location_id uuid NOT NULL REFERENCES locations(id), supplier_id integer NOT NULL REFERENCES suppliers(id), depot_id integer NOT NULL, year integer NOT NULL, color text NOT NULL, license_plate text NOT NULL UNIQUE, transmission text NOT NULL, fuel_type text NOT NULL, seats integer NOT NULL CHECK(seats>0), doors integer NOT NULL CHECK(doors>0), bag_capacity integer NOT NULL DEFAULT 2, price_per_day numeric(12,2) NOT NULL CHECK(price_per_day>0), mileage integer NOT NULL DEFAULT 0, description text NOT NULL DEFAULT '', status text NOT NULL CHECK(status IN ('AVAILABLE','RESERVED','RENTED','MAINTENANCE','INACTIVE')), active boolean NOT NULL DEFAULT true, FOREIGN KEY(model_id,brand_id) REFERENCES vehicle_models(id,brand_id), FOREIGN KEY(depot_id,supplier_id) REFERENCES depots(id,supplier_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE search_contexts (id uuid PRIMARY KEY, affiliate numeric NOT NULL, context jsonb NOT NULL, results uuid[] NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE holds (id uuid PRIMARY KEY, vehicle_id uuid NOT NULL REFERENCES vehicles(id), owner_id text NOT NULL, search_id uuid NOT NULL REFERENCES search_contexts(id), starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, price_per_day numeric(12,2) NOT NULL, currency text NOT NULL, expires_at timestamptz NOT NULL, consumed boolean NOT NULL DEFAULT false, CHECK(starts_at<ends_at), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE order_previews (id uuid PRIMARY KEY, vehicle_id uuid NOT NULL REFERENCES vehicles(id), owner_id text NOT NULL, hold_id uuid REFERENCES holds(id), route jsonb NOT NULL, price_per_day numeric(12,2) NOT NULL, total_amount numeric(12,2) NOT NULL, currency text NOT NULL, extras jsonb NOT NULL DEFAULT '[]', expires_at timestamptz NOT NULL, consumed boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE orders (id uuid PRIMARY KEY, vehicle_id uuid NOT NULL REFERENCES vehicles(id), owner_id text NOT NULL, preview_id uuid NOT NULL UNIQUE REFERENCES order_previews(id), locator text NOT NULL UNIQUE, status text NOT NULL CHECK(status IN ('CONFIRMED','CANCELLED','PENDING')), route jsonb NOT NULL, starts_at timestamptz NOT NULL, ends_at timestamptz NOT NULL, price_per_day numeric(12,2) NOT NULL, total_amount numeric(12,2) NOT NULL, currency text NOT NULL, extras jsonb NOT NULL DEFAULT '[]', vehicle_details jsonb NOT NULL, driver_details jsonb NOT NULL, payment_reference text NOT NULL, CHECK(starts_at<ends_at), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency_records (owner_id text NOT NULL, operation text NOT NULL, key uuid NOT NULL, request_hash text NOT NULL, status_code integer NOT NULL, response_body jsonb, PRIMARY KEY(owner_id,operation,key), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE favorites (id uuid PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), vehicle_id uuid NOT NULL REFERENCES vehicles(id), UNIQUE(user_id,vehicle_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_subscriptions (id uuid PRIMARY KEY, owner_id text NOT NULL, url text NOT NULL, events jsonb NOT NULL, encrypted_secret text, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_outbox (id uuid PRIMARY KEY, owner_id text, event_type text NOT NULL, resource_id text NOT NULL, data jsonb NOT NULL, dispatched boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE webhook_delivery_attempts (id uuid PRIMARY KEY, event_id uuid NOT NULL REFERENCES webhook_outbox(id), subscription_id uuid NOT NULL REFERENCES webhook_subscriptions(id), attempt_count integer NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'PENDING', next_attempt_at timestamptz NOT NULL DEFAULT now(), last_error text, last_status integer, UNIQUE(event_id,subscription_id), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX orders_availability ON orders(vehicle_id,starts_at,ends_at) WHERE status IN ('CONFIRMED','PENDING');
CREATE INDEX holds_availability ON holds(vehicle_id,starts_at,ends_at,expires_at) WHERE NOT consumed;
CREATE INDEX orders_owner ON orders(owner_id);
CREATE INDEX searches_expiry ON search_contexts(expires_at);
CREATE INDEX webhooks_owner ON webhook_subscriptions(owner_id);
CREATE INDEX deliveries_pending ON webhook_delivery_attempts(status,next_attempt_at);
CREATE INDEX vehicles_catalog ON vehicles(depot_id,category_id,status) WHERE active;`);
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    if (process.env.NODE_ENV === 'production')
      throw new Error('Revert deshabilitado en producción.');
    await queryRunner.query(`DROP TABLE webhook_delivery_attempts;
DROP TABLE webhook_outbox;
DROP TABLE webhook_subscriptions;
DROP TABLE favorites;
DROP TABLE idempotency_records;
DROP TABLE orders;
DROP TABLE order_previews;
DROP TABLE holds;
DROP TABLE search_contexts;
DROP TABLE vehicles;
DROP TABLE depot_scores;
DROP TABLE depots;
DROP TABLE suppliers;
DROP TABLE locations;
DROP TABLE categories;
DROP TABLE vehicle_models;
DROP TABLE brands;
DROP TABLE users;`);
  }
}
